### ISSUE TITLE
replace fdosani with edgetest-dev in all the places

### ISSUE THREAD

**Issue by fdosani** [edgetest-dev/run-edgetest-action#17]
Basic house keeping time as described above now that the repo is centralized.

**Comment by jdawang** [comment]
I can do this one

**Comment by Aditi840** [comment]
@fdosani , is this issue still open, I would like to work on it, just give me an overview on what needs to be done.

**Comment by fdosani** [comment]
> @fdosani , is this issue still open, I would like to work on it, just give me an overview on what needs to be done.

@Aditi840 thanks for wanting to help out. I think @jdawang already has a PR for it.
